#ifndef _core_ieee_std_1003dot1_errors_AddressNotAvailable
#define _core_ieee_std_1003dot1_errors_AddressNotAvailable ::core_ieee_std_1003dot1_errors_AddressNotAvailable

struct core_ieee_std_1003dot1_errors_AddressNotAvailable {
};

#endif
