#ifndef _core_ieee_std_1003dot1_errors_AddressFamilyNotSupported
#define _core_ieee_std_1003dot1_errors_AddressFamilyNotSupported ::core_ieee_std_1003dot1_errors_AddressFamilyNotSupported

struct core_ieee_std_1003dot1_errors_AddressFamilyNotSupported {
};

#endif
