#ifndef _core_ieee_std_1003dot1_errors_BadMessage
#define _core_ieee_std_1003dot1_errors_BadMessage ::core_ieee_std_1003dot1_errors_BadMessage

struct core_ieee_std_1003dot1_errors_BadMessage {
};

#endif
