#ifndef _core_ieee_std_1003dot1_errors_BrokenPipe
#define _core_ieee_std_1003dot1_errors_BrokenPipe ::core_ieee_std_1003dot1_errors_BrokenPipe

struct core_ieee_std_1003dot1_errors_BrokenPipe {
};

#endif
