#ifndef _core_ieee_std_1003dot1_errors_ConnectionTimedOut
#define _core_ieee_std_1003dot1_errors_ConnectionTimedOut ::core_ieee_std_1003dot1_errors_ConnectionTimedOut

struct core_ieee_std_1003dot1_errors_ConnectionTimedOut {
};

#endif
