#ifndef _core_ieee_std_1003dot1_errors_ConnectionReset
#define _core_ieee_std_1003dot1_errors_ConnectionReset ::core_ieee_std_1003dot1_errors_ConnectionReset

struct core_ieee_std_1003dot1_errors_ConnectionReset {
};

#endif
