#ifndef _core_ieee_std_1003dot1_errors_ConnectionRefused
#define _core_ieee_std_1003dot1_errors_ConnectionRefused ::core_ieee_std_1003dot1_errors_ConnectionRefused

struct core_ieee_std_1003dot1_errors_ConnectionRefused {
};

#endif
