#ifndef _core_ieee_std_1003dot1_errors_ConnectionAlreadyInProgress
#define _core_ieee_std_1003dot1_errors_ConnectionAlreadyInProgress ::core_ieee_std_1003dot1_errors_ConnectionAlreadyInProgress

struct core_ieee_std_1003dot1_errors_ConnectionAlreadyInProgress {
};

#endif
