#ifndef _core_ieee_std_1003dot1_errors_CrossDeviceLink
#define _core_ieee_std_1003dot1_errors_CrossDeviceLink ::core_ieee_std_1003dot1_errors_CrossDeviceLink

struct core_ieee_std_1003dot1_errors_CrossDeviceLink {
};

#endif
