#ifndef _core_ieee_std_1003dot1_errors_DestinationAddressRequired
#define _core_ieee_std_1003dot1_errors_DestinationAddressRequired ::core_ieee_std_1003dot1_errors_DestinationAddressRequired

struct core_ieee_std_1003dot1_errors_DestinationAddressRequired {
};

#endif
