#ifndef _core_ieee_std_1003dot1_errors_NoSuchProcess
#define _core_ieee_std_1003dot1_errors_NoSuchProcess ::core_ieee_std_1003dot1_errors_NoSuchProcess

struct core_ieee_std_1003dot1_errors_NoSuchProcess {
};

#endif
