#ifndef _core_ieee_std_1003dot1_errors_OperationNotSupportedOnSocket
#define _core_ieee_std_1003dot1_errors_OperationNotSupportedOnSocket ::core_ieee_std_1003dot1_errors_OperationNotSupportedOnSocket

struct core_ieee_std_1003dot1_errors_OperationNotSupportedOnSocket {
};

#endif
