#ifndef _core_ieee_std_1003dot1_errors_PermissionDenied
#define _core_ieee_std_1003dot1_errors_PermissionDenied ::core_ieee_std_1003dot1_errors_PermissionDenied

struct core_ieee_std_1003dot1_errors_PermissionDenied {
};

#endif
