#ifndef _core_ieee_std_1003dot1_errors_ProtocolError
#define _core_ieee_std_1003dot1_errors_ProtocolError ::core_ieee_std_1003dot1_errors_ProtocolError

struct core_ieee_std_1003dot1_errors_ProtocolError {
};

#endif
