#ifndef _core_ieee_std_1003dot1_errors_ProtocolNotSupported
#define _core_ieee_std_1003dot1_errors_ProtocolNotSupported ::core_ieee_std_1003dot1_errors_ProtocolNotSupported

struct core_ieee_std_1003dot1_errors_ProtocolNotSupported {
};

#endif
