#ifndef _core_ieee_std_1003dot1_errors_ResourceTemporarilyUnavailable
#define _core_ieee_std_1003dot1_errors_ResourceTemporarilyUnavailable ::core_ieee_std_1003dot1_errors_ResourceTemporarilyUnavailable

struct core_ieee_std_1003dot1_errors_ResourceTemporarilyUnavailable {
};

#endif
