#ifndef _core_io_socket_protocols_Ipv4
#define _core_io_socket_protocols_Ipv4 ::core_io_socket_protocols_Ipv4

#include <core/preprocessor/define_generic_opaque_type_alias.h>

_core_preprocessor_define_generic_opaque_type_alias(core_io_socket_protocols_Ipv4);

#endif
