#ifndef _core_io_socket_protocols_Packet
#define _core_io_socket_protocols_Packet ::core_io_socket_protocols_Packet

#include <core/preprocessor/define_generic_opaque_type_alias.h>

_core_preprocessor_define_generic_opaque_type_alias(core_io_socket_protocols_Packet);

#endif
