#ifndef _core_io_socket_types_Stream
#define _core_io_socket_types_Stream ::core_io_socket_types_Stream

#include <core/preprocessor/define_generic_opaque_type_alias.h>

_core_preprocessor_define_generic_opaque_type_alias(core_io_socket_types_Stream);

#endif
