#include <core/Array.type.h>
#include <core/Ascii.type.h>
#include <core/Base_object.type.h>
#include <core/C_string.type.h>
#include <core/Coproduct.type.h>
#include <core/Default_tagged_union.type.h>
#include <core/False.type.h>
#include <core/Fmap.type.h>
#include <core/Hash_set.type.h>
#include <core/Hash_table.type.h>
#include <core/Hextet.type.h>
#include <core/LessThanSignedSizeMax.type.h>
#include <core/Literal.type.h>
#include <core/Maybe.type.h>
#include <core/Nil.type.h>
#include <core/Null_terminated_string.type.h>
#include <core/Nullptr.type.h>
#include <core/Nullptr_if.type.h>
#include <core/Octet.type.h>
#include <core/Octlet.type.h>
#include <core/Pointer.type.h>
#include <core/Product.type.h>
#include <core/Quadlet.type.h>
#include <core/Remove_all_qualifiers.type.h>
#include <core/Remove_const_qualifier.type.h>
#include <core/Remove_cv_qualifiers.type.h>
#include <core/Remove_ref_qualifier.type.h>
#include <core/Remove_volatile_qualifier.type.h>
#include <core/Signed_hextet.type.h>
#include <core/Signed_octet.type.h>
#include <core/Signed_octlet.type.h>
#include <core/Signed_quadlet.type.h>
#include <core/Simple_tagged_union.type.h>
#include <core/Size.type.h>
#include <core/Sum.type.h>
#include <core/Tagged_union.type.h>
#include <core/Targets.type.h>
#include <core/Tree.type.h>
#include <core/Trie.type.h>
#include <core/True.type.h>
#include <core/Untagged_union.type.h>
#include <core/Utf8.type.h>
#include <core/apply.h>
#include <core/array/allocate.h>
#include <core/array/base_address.h>
#include <core/array/deallocate.h>
#include <core/array/grow.h>
#include <core/array/resize.h>
#include <core/array/shrink.h>
#include <core/array/size.h>
#include <core/base_object.h>
#include <core/com/apple/quartz/render.h>
#include <core/com/microsoft/directx/render.h>
#include <core/complement.h>
#include <core/file/Handle.type.h>
#include <core/file/Read_only_handle.type.h>
#include <core/file/Read_write_handle.type.h>
#include <core/file/Status.type.h>
#include <core/file/Write_only_handle.type.h>
#include <core/file/handle/allocate.h>
#include <core/file/handle/allocate_read_only.h>
#include <core/file/handle/allocate_read_write.h>
#include <core/file/handle/allocate_write_only.h>
#include <core/file/handle/deallocate.h>
#include <core/file/handle/read_data.h>
#include <core/file/handle/seek.h>
#include <core/file/handle/seek_origins/Begin.type.h>
#include <core/file/handle/seek_origins/Current.type.h>
#include <core/file/handle/seek_origins/End.type.h>
#include <core/file/handle/write.h>
#include <core/file/status.h>
#include <core/file/status/device_id.h>
#include <core/file/status/group_id.h>
#include <core/file/status/inode_number.h>
#include <core/file/status/mode.h>
#include <core/file/status/number_of_hard_link.h>
#include <core/file/status/size.h>
#include <core/file/status/user_id.h>
#include <core/freebsd/kqueue/Handle.type.h>
#include <core/freebsd/kqueue/handle/allocate.h>
#include <core/freebsd/kqueue/handle/deallocate.h>
#include <core/graphics/node/attributes.h>
#include <core/graphics/node/children.h>
#include <core/hash_table/Default_hash_function.type.h>
#include <core/hash_table/buckets.h>
#include <core/hash_table/hash_function.h>
#include <core/hash_table/insert.h>
#include <core/hash_table/max_size.h>
#include <core/hash_table/size.h>
#include <core/iana/assignments/http_status_codes/continue.h>
#include <core/iana/assignments/http_status_codes/switching_protocols.h>
#include <core/id.h>
#include <core/ieee/std/1003dot1/Error.type.h>
#include <core/ieee/std/1003dot1/Iovec.type.h>
#include <core/ieee/std/1003dot1/Memory.type.h>
#include <core/ieee/std/1003dot1/Time.type.h>
#include <core/ieee/std/1003dot1/current_time.h>
#include <core/ieee/std/1003dot1/environment/get.h>
#include <core/ieee/std/1003dot1/environment/get_home.h>
#include <core/ieee/std/1003dot1/environment/get_lang.h>
#include <core/ieee/std/1003dot1/environment/get_pwd.h>
#include <core/ieee/std/1003dot1/environment/set.h>
#include <core/ieee/std/1003dot1/environment/unset.h>
#include <core/ieee/std/1003dot1/errors/AddressFamilyNotSupported.type.h>
#include <core/ieee/std/1003dot1/errors/AddressInUse.type.h>
#include <core/ieee/std/1003dot1/errors/AddressNotAvailable.type.h>
#include <core/ieee/std/1003dot1/errors/ArgumentListTooLong.type.h>
#include <core/ieee/std/1003dot1/errors/BadAddress.type.h>
#include <core/ieee/std/1003dot1/errors/BadFileDescriptor.type.h>
#include <core/ieee/std/1003dot1/errors/BadMessage.type.h>
#include <core/ieee/std/1003dot1/errors/BrokenPipe.type.h>
#include <core/ieee/std/1003dot1/errors/ConnectionAborted.type.h>
#include <core/ieee/std/1003dot1/errors/ConnectionAlreadyInProgress.type.h>
#include <core/ieee/std/1003dot1/errors/ConnectionRefused.type.h>
#include <core/ieee/std/1003dot1/errors/ConnectionReset.type.h>
#include <core/ieee/std/1003dot1/errors/ConnectionTimedOut.type.h>
#include <core/ieee/std/1003dot1/errors/CrossDeviceLink.type.h>
#include <core/ieee/std/1003dot1/errors/DestinationAddressRequired.type.h>
#include <core/ieee/std/1003dot1/errors/DomainError.type.h>
#include <core/ieee/std/1003dot1/errors/FileExists.type.h>
#include <core/ieee/std/1003dot1/errors/HostIsUnreachable.type.h>
#include <core/ieee/std/1003dot1/errors/InappropriateIoControlOperation.type.h>
#include <core/ieee/std/1003dot1/errors/IoError.type.h>
#include <core/ieee/std/1003dot1/errors/NoChildProcesses.type.h>
#include <core/ieee/std/1003dot1/errors/NoSuchDevice.type.h>
#include <core/ieee/std/1003dot1/errors/NoSuchDeviceOrAddress.type.h>
#include <core/ieee/std/1003dot1/errors/NoSuchFileOrDirectory.type.h>
#include <core/ieee/std/1003dot1/errors/NoSuchProcess.type.h>
#include <core/ieee/std/1003dot1/errors/NotSupported.type.h>
#include <core/ieee/std/1003dot1/errors/OperationCanceled.type.h>
#include <core/ieee/std/1003dot1/errors/OperationNotPermitted.type.h>
#include <core/ieee/std/1003dot1/errors/OperationNotSupportedOnSocket.type.h>
#include <core/ieee/std/1003dot1/errors/PermissionDenied.type.h>
#include <core/ieee/std/1003dot1/errors/PreviousOwnerDied.type.h>
#include <core/ieee/std/1003dot1/errors/ProtocolError.type.h>
#include <core/ieee/std/1003dot1/errors/ProtocolNotSupported.type.h>
#include <core/ieee/std/1003dot1/errors/ResourceBusy.type.h>
#include <core/ieee/std/1003dot1/errors/ResourceDeadlockWouldOccur.type.h>
#include <core/ieee/std/1003dot1/errors/ResourceTemporarilyUnavailable.type.h>
#include <core/ieee/std/1003dot1/file/Status.type.h>
#include <core/ieee/std/1003dot1/file/status.h>
#include <core/ieee/std/1003dot1/file/status/device_id.h>
#include <core/ieee/std/1003dot1/file/status/group_id.h>
#include <core/ieee/std/1003dot1/file/status/inode_number.h>
#include <core/ieee/std/1003dot1/file/status/mode.h>
#include <core/ieee/std/1003dot1/file/status/number_of_hard_link.h>
#include <core/ieee/std/1003dot1/file/status/size.h>
#include <core/ieee/std/1003dot1/file/status/user_id.h>
#include <core/ieee/std/1003dot1/iovec/base_address.h>
#include <core/ieee/std/1003dot1/iovec/from.h>
#include <core/ieee/std/1003dot1/iovec/size.h>
#include <core/ieee/std/1003dot1/last_error.h>
#include <core/ieee/std/1003dot1/memory/allocate.h>
#include <core/ieee/std/1003dot1/memory/deallocate.h>
#include <core/ieee/std/1003dot1/memory/reallocate.h>
#include <core/ietf/rfc/3986/Path.type.h>
#include <core/ietf/rfc/3986/Uri.type.h>
#include <core/ietf/rfc/7231/status_continue.h>
#include <core/ietf/rfc/7231/status_ok.h>
#include <core/io/print.h>
#include <core/io/print_line.h>
#include <core/io/socket/Handle.type.h>
#include <core/io/socket/handle/allocate.h>
#include <core/io/socket/handle/bind.h>
#include <core/io/socket/handle/deallocate.h>
#include <core/io/socket/protocols/Ipv4.type.h>
#include <core/io/socket/protocols/Ipv6.type.h>
#include <core/io/socket/protocols/Local.type.h>
#include <core/io/socket/protocols/Packet.type.h>
#include <core/io/socket/protocols/Unix.type.h>
#include <core/io/socket/types/Datagram.type.h>
#include <core/io/socket/types/Raw.type.h>
#include <core/io/socket/types/Stream.type.h>
#include <core/is.h>
#include <core/is_equal_to.h>
#include <core/is_not_equal_to.h>
#include <core/iterable/fetch.h>
#include <core/iterable/iterator.h>
#include <core/join.h>
#include <core/json/Null.type.h>
#include <core/jwk/alg.h>
#include <core/jwk/key_ops.h>
#include <core/jwk/kid.h>
#include <core/jwk/kty.h>
#include <core/jwk/set/keys.h>
#include <core/jwk/use.h>
#include <core/jwk/x5c.h>
#include <core/jwk/x5t.h>
#include <core/jwk/x5t_s256.h>
#include <core/jwk/x5u.h>
#include <core/jws/header.h>
#include <core/jws/header/typ.h>
#include <core/jws/payload.h>
#include <core/jws/signature.h>
#include <core/jwt/aud.h>
#include <core/jwt/audience.h>
#include <core/jwt/exp.h>
#include <core/jwt/expiration_time.h>
#include <core/jwt/iat.h>
#include <core/jwt/iss.h>
#include <core/jwt/issued_at.h>
#include <core/jwt/issuer.h>
#include <core/jwt/jti.h>
#include <core/jwt/jwt_id.h>
#include <core/jwt/nbf.h>
#include <core/jwt/not_before.h>
#include <core/jwt/sub.h>
#include <core/jwt/subject.h>
#include <core/length.h>
#include <core/linux/epoll/Handle.type.h>
#include <core/linux/epoll/handle/add.h>
#include <core/linux/epoll/handle/allocate.h>
#include <core/linux/epoll/handle/deallocate.h>
#include <core/linux/epoll/handle/remove.h>
#include <core/linux/signal/handle/allocate.h>
#include <core/linux/signal/handle/deallocate.h>
#include <core/linux/timer/handle/allocate.h>
#include <core/linux/timer/handle/deallocate.h>
#include <core/mathematics/ComposedMap.type.h>
#include <core/mathematics/Coproduct.type.h>
#include <core/mathematics/Product.type.h>
#include <core/mathematics/Product0.type.h>
#include <core/mathematics/Product1.type.h>
#include <core/mathematics/Product2.type.h>
#include <core/mathematics/Product3.type.h>
#include <core/mathematics/Projection.type.h>
#include <core/mathematics/Sum.type.h>
#include <core/mathematics/complement.h>
#include <core/mathematics/digits.h>
#include <core/mathematics/equals.h>
#include <core/mathematics/id.h>
#include <core/mathematics/is_equal_to.h>
#include <core/mathematics/is_greater_than_or_equal_to.h>
#include <core/mathematics/is_less_than_or_equal_to.h>
#include <core/mathematics/is_not_equal_to.h>
#include <core/mathematics/join.h>
#include <core/mathematics/logic/False.type.h>
#include <core/mathematics/logic/True.type.h>
#include <core/mathematics/map/apply.h>
#include <core/mathematics/map/call_with_indices.h>
#include <core/mathematics/meet.h>
#include <core/mathematics/set/Union.type.h>
#include <core/mathematics/set/contains.h>
#include <core/mathematics/set/is_subset_of.h>
#include <core/mathematics/tuple/concat.h>
#include <core/mathematics/tuple/length.h>
#include <core/mathematics/tuple/slice.h>
#include <core/mathematics/tuple/sort.h>
#include <core/meet.h>
#include <core/memory/address.h>
#include <core/memory/address/dereference.h>
#include <core/memory/allocate.h>
#include <core/memory/deallocate.h>
#include <core/memory/reallocate.h>
#include <core/meta/Conditional.type.h>
#include <core/meta/Multiset.type.h>
#include <core/meta/Set.type.h>
#include <core/meta/Tuple.type.h>
#include <core/meta/card.h>
#include <core/meta/contains.h>
#include <core/meta/declval.h>
#include <core/meta/index.h>
#include <core/meta/is_aggregate_initializable.h>
#include <core/meta/is_const_qualified.h>
#include <core/meta/is_convertible.h>
#include <core/meta/is_defined.h>
#include <core/meta/is_equal_to.h>
#include <core/meta/is_invocable.h>
#include <core/meta/is_lvalue_reference.h>
#include <core/meta/is_rvalue_reference.h>
#include <core/meta/is_struct.h>
#include <core/meta/is_subset_of.h>
#include <core/meta/is_unit_type.h>
#include <core/meta/length.h>
#include <core/meta/mathematics/Multiset.type.h>
#include <core/meta/mathematics/Set.type.h>
#include <core/meta/mathematics/Tuple.type.h>
#include <core/meta/mathematics/is_equal_to.h>
#include <core/meta/mathematics/multiset/multiplicity.h>
#include <core/meta/mathematics/set/Difference.type.h>
#include <core/meta/mathematics/set/Union.type.h>
#include <core/meta/mathematics/set/card.h>
#include <core/meta/mathematics/set/contains.h>
#include <core/meta/mathematics/set/is_subset_of.h>
#include <core/meta/mathematics/tuple/length.h>
#include <core/meta/multiplicity.h>
#include <core/meta/optimized.h>
#include <core/netbsd/kqueue/Handle.type.h>
#include <core/netbsd/kqueue/handle/allocate.h>
#include <core/netbsd/kqueue/handle/deallocate.h>
#include <core/openbsd/kqueue/Handle.type.h>
#include <core/openbsd/kqueue/handle/allocate.h>
#include <core/openbsd/kqueue/handle/deallocate.h>
#include <core/operator""_array.h>
#include <core/operator""_c_string.h>
#include <core/operator""_literal.h>
#include <core/preprocessor/define_generic_opaque_type_alias.h>
#include <core/preprocessor/define_map.h>
#include <core/preprocessor/define_opaque_type_alias.h>
#include <core/preprocessor/end.h>
#include <core/preprocessor/for_each.h>
#include <core/preprocessor/lambda.h>
#include <core/print.h>
#include <core/print_line.h>
#include <core/process/environment/get.h>
#include <core/process/environment/set.h>
#include <core/process/environment/unset.h>
#include <core/process/error_stream.h>
#include <core/process/input_stream.h>
#include <core/process/output_stream.h>
#include <core/projection.h>
#include <core/queue/dequeue.h>
#include <core/queue/enqueue.h>
#include <core/stack/pop.h>
#include <core/stack/push.h>
#include <core/string/from.h>
#include <core/system/Error.type.h>
#include <core/system/Time.type.h>
#include <core/system/current_time.h>
#include <core/tagged_union/Hoge.type.h>
#include <core/tagged_union/Tag.type.h>
#include <core/tagged_union/Unsafe_cast.h>
#include <core/tagged_union/tag.h>
#include <core/thread/signal_mask.h>
#include <core/unicode/ScalarValue.type.h>
#include <core/unicode/Utf8.type.h>
#include <core/unicode/utf16/CodeUnit.type.h>
#include <core/unicode/utf32/CodeUnit.type.h>
#include <core/unicode/utf8/CodeUnit.type.h>
#include <core/unicode/utf8/decode.h>
#include <core/untagged_union/Unsafe_cast.h>
#include <core/wayland/get.h>
#include <core/wayland/render.h>
#include <core/whatwg/url/Percent_encoded_byte.type.h>
#include <core/x/Connection.type.h>
#include <core/x/error/DisplayIsNotSet.type.h>
#include <core/x/screen/render.h>
